---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ex1-go-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: ex1-go-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      labels:
        name: ex1-go-server
    spec:
      containers:
        - env:
          image: "ex1-go-server:latest"
          imagePullPolicy: IfNotPresent
          name: ex1-go-server
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        containerNames:
          - ex1-go-server
        from:
          kind: ImageStreamTag
          name: 'ex1-go-server:latest'
          namespace: cq-oc-tutorial
      type: ImageChange