---
apiVersion: v1
kind: Service
metadata:
  name: ex1-go-server   
spec:
  selector:                  
    name: ex1-go-server
  ports:
  - name: 64912-tcp
    port: 64912               
    protocol: TCP
    targetPort: 64912
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  labels:
    name: ex1-go-server
  name: ex1-go-server
spec:
  host: ex1-go-server.app.cmr.wob.vw.vwg
  path: /
  port:
    targetPort: 64912-tcp 
  to:
    kind: Service
    name: ex1-go-server