---
apiVersion: v1
kind: Template
labels:
  template: service-template
metadata:
  annotations:
    description: |-
      Service Template
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME} 
  spec:
    selector:                  
      name: ${APP_NAME}
    ports:
    - name: ${APP_PORT}-tcp
      port: 64912              
      protocol: TCP
      targetPort: 64912
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${APP_NAME}.app.cmr.wob.vw.vwg
    path: /
    port:
      targetPort: "64912-tcp"
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
- name: APP_PORT
  displayName: Port
  description: The port assigned to the service
  required: true
